name: flutter_diy_print
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_country_picker: ^0.1.6 #国家选择器 
  international_phone_input: ^1.0.2 #国家选择器
  percent_indicator: ^2.1.1+1 #进度指示器
  flutter_screenutil: ^0.7.0
  provider: ^3.2.0     
  dio: ^3.0.7          #网络请求
  barcode_scan: ^1.0.0  #扫描二维码
  flutter_spinkit: ^4.1.1+1 #loading动画
  shared_preferences: ^0.5.6+3 #本地存储
  oktoast: ^2.3.0 #提示弹框
  flutter_swiper: ^1.1.6 #轮播 
  # image_picker: ^0.6.3+4
  transparent_image: ^1.0.0 #图片加载占位符 
  flutter_easyrefresh: ^2.0.9 #上拉（下拉）刷新
  flutter_facebook_login: ^1.2.0
  flutter_localizations: #多语言
    sdk: flutter
  flutter_datetime_picker: ^1.3.5 #日期选择器
  gender_selection: ^1.0.0 #男女选择
dev_dependencies:
  flutter_test:   
    sdk: flutter 

 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.jpg
    - assets/images/noData.jpeg
    - assets/images/login_image/
    - assets/images/register/
    - assets/images/workspace/
    - assets/images/tabbar/
    - assets/images/account/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: iconfont
      fonts:
          - asset: assets/fonts/iconfont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
